name: CI/CD Pipeline for backend services

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1  

jobs:
  build:
    name: Build and containerize all services 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node for buyer_service
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.0'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies for buyer_service
        run: npm ci
        
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: 'Dockerfile'
          image: ${{ secrets.DOCKER_USERNAME_N }}/buyer-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_N }}
          password: ${{ secrets.DOCKER_PASSWORD_N }}

    ## Repeat steps Install dependencies and build docker image for other services here

  deploy: 
    name: Deploy services to k8s cluster
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Deploying buyer_service
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f kubernetes
